from django.core.management.base import BaseCommand
from library_app.models import Book
import random

class Command(BaseCommand):
    help = "Seed the database with sample books"

    def handle(self, *args, **kwargs):
        sample_books = [
    {"title": "To Kill a Mockingbird", "author": "Harper Lee", "genre": "Fiction", "description": "A novel about racial injustice and moral growth in the American South."},
    {"title": "1984", "author": "George Orwell", "genre": "Dystopian", "description": "A chilling vision of a totalitarian regime and constant surveillance."},
    {"title": "Pride and Prejudice", "author": "Jane Austen", "genre": "Romance", "description": "A witty story about love, reputation, and class in 19th-century England."},
    {"title": "The Great Gatsby", "author": "F. Scott Fitzgerald", "genre": "Classic", "description": "The tragedy of Jay Gatsby and the corruption of the American Dream."},
    {"title": "Moby-Dick", "author": "Herman Melville", "genre": "Adventure", "description": "Captain Ahab’s obsessive quest for revenge against the white whale."},
    {"title": "Jane Eyre", "author": "Charlotte Brontë", "genre": "Romance", "description": "A young orphan’s struggle for love, independence, and equality."},
    {"title": "The Catcher in the Rye", "author": "J.D. Salinger", "genre": "Fiction", "description": "Holden Caulfield’s journey through teenage rebellion and alienation."},
    {"title": "The Hobbit", "author": "J.R.R. Tolkien", "genre": "Fantasy", "description": "Bilbo Baggins embarks on an epic quest with dwarves and a wizard."},
    {"title": "Brave New World", "author": "Aldous Huxley", "genre": "Dystopian", "description": "A futuristic world where technology and pleasure control society."},
    {"title": "War and Peace", "author": "Leo Tolstoy", "genre": "Historical", "description": "An epic about Russian aristocracy and Napoleon’s invasion."},
    {"title": "Wuthering Heights", "author": "Emily Brontë", "genre": "Gothic", "description": "A tragic romance of passion, revenge, and generational curses."},
    {"title": "Crime and Punishment", "author": "Fyodor Dostoevsky", "genre": "Philosophical", "description": "The mental torment of a student who commits a murder."},
    {"title": "Anna Karenina", "author": "Leo Tolstoy", "genre": "Romance", "description": "A doomed love affair in the backdrop of Russian high society."},
    {"title": "The Odyssey", "author": "Homer", "genre": "Epic", "description": "Odysseus’s long journey home after the Trojan War."},
    {"title": "The Iliad", "author": "Homer", "genre": "Epic", "description": "The story of the Trojan War and Achilles’ wrath."},
    {"title": "The Divine Comedy", "author": "Dante Alighieri", "genre": "Poetry", "description": "A journey through Hell, Purgatory, and Paradise."},
    {"title": "Les Misérables", "author": "Victor Hugo", "genre": "Historical", "description": "The struggles of ex-convict Jean Valjean and revolutionary France."},
    {"title": "Great Expectations", "author": "Charles Dickens", "genre": "Classic", "description": "The coming-of-age of Pip, an orphan with big dreams."},
    {"title": "David Copperfield", "author": "Charles Dickens", "genre": "Classic", "description": "A semi-autobiographical tale of personal growth and resilience."},
    {"title": "A Tale of Two Cities", "author": "Charles Dickens", "genre": "Historical", "description": "Love, sacrifice, and revolution during the French Revolution."},
    {"title": "The Brothers Karamazov", "author": "Fyodor Dostoevsky", "genre": "Philosophical", "description": "A deep exploration of faith, morality, and family conflict."},
    {"title": "Madame Bovary", "author": "Gustave Flaubert", "genre": "Realism", "description": "Emma Bovary’s pursuit of passion and luxury ends in tragedy."},
    {"title": "Don Quixote", "author": "Miguel de Cervantes", "genre": "Satire", "description": "The misadventures of an idealistic knight and his loyal squire."},
    {"title": "The Alchemist", "author": "Paulo Coelho", "genre": "Fable", "description": "A shepherd’s journey to discover his personal legend."},
    {"title": "The Old Man and the Sea", "author": "Ernest Hemingway", "genre": "Adventure", "description": "A fisherman’s epic struggle against a giant marlin."},
    {"title": "For Whom the Bell Tolls", "author": "Ernest Hemingway", "genre": "War", "description": "A young American fights in the Spanish Civil War."},
    {"title": "The Sun Also Rises", "author": "Ernest Hemingway", "genre": "Classic", "description": "Expatriates searching for meaning after World War I."},
    {"title": "Catch-22", "author": "Joseph Heller", "genre": "Satire", "description": "A darkly comedic take on war and bureaucracy."},
    {"title": "Fahrenheit 451", "author": "Ray Bradbury", "genre": "Dystopian", "description": "A society where books are banned and burned by firemen."},
    {"title": "Slaughterhouse-Five", "author": "Kurt Vonnegut", "genre": "Science Fiction", "description": "Billy Pilgrim’s surreal journey through time and war."},
    {"title": "Lord of the Flies", "author": "William Golding", "genre": "Allegory", "description": "Boys stranded on an island descend into savagery."},
    {"title": "Of Mice and Men", "author": "John Steinbeck", "genre": "Tragedy", "description": "The bond and dreams of two displaced migrant workers."},
    {"title": "The Grapes of Wrath", "author": "John Steinbeck", "genre": "Historical", "description": "A family’s struggle during the Great Depression."},
    {"title": "East of Eden", "author": "John Steinbeck", "genre": "Classic", "description": "A modern retelling of the story of Cain and Abel."},
    {"title": "Beloved", "author": "Toni Morrison", "genre": "Historical", "description": "The haunting legacy of slavery on a mother and daughter."},
    {"title": "Song of Solomon", "author": "Toni Morrison", "genre": "Fiction", "description": "An African American man’s search for identity and roots."},
    {"title": "Invisible Man", "author": "Ralph Ellison", "genre": "Fiction", "description": "A Black man’s journey through racism and invisibility."},
    {"title": "Things Fall Apart", "author": "Chinua Achebe", "genre": "Historical", "description": "The clash of Igbo tradition and British colonialism."},
    {"title": "One Hundred Years of Solitude", "author": "Gabriel García Márquez", "genre": "Magical Realism", "description": "The rise and fall of the Buendía family in Macondo."},
    {"title": "Love in the Time of Cholera", "author": "Gabriel García Márquez", "genre": "Romance", "description": "A love story spanning decades of waiting and persistence."},
    {"title": "The Kite Runner", "author": "Khaled Hosseini", "genre": "Drama", "description": "A friendship and betrayal in Afghanistan."},
    {"title": "A Thousand Splendid Suns", "author": "Khaled Hosseini", "genre": "Drama", "description": "Two Afghan women form a bond amid war and hardship."},
    {"title": "Life of Pi", "author": "Yann Martel", "genre": "Adventure", "description": "A boy stranded on a lifeboat with a Bengal tiger."},
    {"title": "The Book Thief", "author": "Markus Zusak", "genre": "Historical", "description": "A young girl’s love of books in Nazi Germany."},
    {"title": "All the Light We Cannot See", "author": "Anthony Doerr", "genre": "Historical", "description": "The lives of a blind French girl and a German boy during WWII."},
    {"title": "Gone with the Wind", "author": "Margaret Mitchell", "genre": "Historical", "description": "The Civil War and Reconstruction seen through Scarlett O’Hara."},
    {"title": "Dracula", "author": "Bram Stoker", "genre": "Gothic", "description": "The battle between Count Dracula and his pursuers."},
    {"title": "Frankenstein", "author": "Mary Shelley", "genre": "Gothic", "description": "A scientist creates life with unintended consequences."},
    {"title": "The Picture of Dorian Gray", "author": "Oscar Wilde", "genre": "Philosophical", "description": "A man remains youthful while his portrait ages."},
    {"title": "The Stranger", "author": "Albert Camus", "genre": "Existential", "description": "An indifferent man faces murder and justice."},
    {"title": "The Metamorphosis", "author": "Franz Kafka", "genre": "Absurdist", "description": "A man wakes up transformed into a giant insect."},
    {"title": "Heart of Darkness", "author": "Joseph Conrad", "genre": "Novella", "description": "A journey up the Congo River into human corruption."},
    {"title": "The Road", "author": "Cormac McCarthy", "genre": "Post-apocalyptic", "description": "A father and son struggle to survive in a ruined world."},
    {"title": "Blood Meridian", "author": "Cormac McCarthy", "genre": "Western", "description": "Violence and lawlessness in the American frontier."},
    {"title": "The Handmaid’s Tale", "author": "Margaret Atwood", "genre": "Dystopian", "description": "A totalitarian society subjugates women into handmaids."},
    {"title": "Oryx and Crake", "author": "Margaret Atwood", "genre": "Science Fiction", "description": "Genetic engineering creates a dystopian future."},
    {"title": "The Bell Jar", "author": "Sylvia Plath", "genre": "Semi-autobiographical", "description": "A young woman’s descent into mental illness."},
    {"title": "Persepolis", "author": "Marjane Satrapi", "genre": "Graphic Memoir", "description": "A girl’s coming-of-age during the Iranian Revolution."},
    {"title": "Maus", "author": "Art Spiegelman", "genre": "Graphic Novel", "description": "A Holocaust survivor’s story told through comics."},
    {"title": "The Color Purple", "author": "Alice Walker", "genre": "Historical", "description": "Letters from an African American woman finding her voice."},
    {"title": "Uncle Tom’s Cabin", "author": "Harriet Beecher Stowe", "genre": "Historical", "description": "A novel that fueled anti-slavery sentiment in America."},
    {"title": "Middlemarch", "author": "George Eliot", "genre": "Classic", "description": "A tale of ambition, marriage, and social change in England."},
    {"title": "The Scarlet Letter", "author": "Nathaniel Hawthorne", "genre": "Classic", "description": "A woman’s punishment for adultery in Puritan New England."},
    {"title": "Their Eyes Were Watching God", "author": "Zora Neale Hurston", "genre": "Romance", "description": "Janie Crawford’s quest for self-discovery and love."},
    {"title": "Siddhartha", "author": "Hermann Hesse", "genre": "Philosophical", "description": "A man’s spiritual journey toward enlightenment."},
    {"title": "Steppenwolf", "author": "Hermann Hesse", "genre": "Philosophical", "description": "A lonely intellectual’s struggle with duality."},
    {"title": "Demian", "author": "Hermann Hesse", "genre": "Coming-of-age", "description": "A young man’s awakening to a new worldview."},
    {"title": "Norwegian Wood", "author": "Haruki Murakami", "genre": "Romance", "description": "A nostalgic story of love and loss in Tokyo."},
    {"title": "Kafka on the Shore", "author": "Haruki Murakami", "genre": "Fantasy", "description": "Two interconnected tales blending reality and dreams."},
    {"title": "1Q84", "author": "Haruki Murakami", "genre": "Fantasy", "description": "A parallel world story filled with mystery and magic."},
    {"title": "The Wind-Up Bird Chronicle", "author": "Haruki Murakami", "genre": "Mystery", "description": "A man searches for his missing wife through strange events."},
    {"title": "The Da Vinci Code", "author": "Dan Brown", "genre": "Thriller", "description": "A symbologist uncovers secrets hidden in art and religion."},
    {"title": "Angels & Demons", "author": "Dan Brown", "genre": "Thriller", "description": "A Harvard professor battles a secret society threatening the Vatican."},
    {"title": "The Girl with the Dragon Tattoo", "author": "Stieg Larsson", "genre": "Mystery", "description": "A journalist and hacker uncover dark family secrets."},
    {"title": "The Girl Who Played with Fire", "author": "Stieg Larsson", "genre": "Mystery", "description": "A continuation of Lisbeth Salander’s story."},
    {"title": "The Girl Who Kicked the Hornets’ Nest", "author": "Stieg Larsson", "genre": "Mystery", "description": "The conclusion of the Millennium Trilogy."},
    {"title": "The Hunger Games", "author": "Suzanne Collins", "genre": "Dystopian", "description": "Children fight to the death in a televised competition."},
    {"title": "Catching Fire", "author": "Suzanne Collins", "genre": "Dystopian", "description": "Katniss Everdeen becomes a symbol of rebellion."},
    {"title": "Mockingjay", "author": "Suzanne Collins", "genre": "Dystopian", "description": "The final battle against the Capitol."},
    {"title": "Harry Potter and the Sorcerer’s Stone", "author": "J.K. Rowling", "genre": "Fantasy", "description": "A boy discovers he is a wizard and attends Hogwarts."},
    {"title": "Harry Potter and the Chamber of Secrets", "author": "J.K. Rowling", "genre": "Fantasy", "description": "Harry uncovers the mystery of the Chamber of Secrets."},
    {"title": "Harry Potter and the Prisoner of Azkaban", "author": "J.K. Rowling", "genre": "Fantasy", "description": "Harry learns about his godfather and past."},
    {"title": "Harry Potter and the Goblet of Fire", "author": "J.K. Rowling", "genre": "Fantasy", "description": "Harry competes in the deadly Triwizard Tournament."},
    {"title": "Harry Potter and the Order of the Phoenix", "author": "J.K. Rowling", "genre": "Fantasy", "description": "Harry fights against Voldemort’s rising power."},
    {"title": "Harry Potter and the Half-Blood Prince", "author": "J.K. Rowling", "genre": "Fantasy", "description": "Harry learns Voldemort’s dark secrets."},
    {"title": "Harry Potter and the Deathly Hallows", "author": "J.K. Rowling", "genre": "Fantasy", "description": "The final showdown between Harry and Voldemort."},
    {"title": "The Lord of the Rings: The Fellowship of the Ring", "author": "J.R.R. Tolkien", "genre": "Fantasy", "description": "Frodo begins his quest to destroy the One Ring."},
    {"title": "The Lord of the Rings: The Two Towers", "author": "J.R.R. Tolkien", "genre": "Fantasy", "description": "The fellowship faces new challenges against Sauron."},
    {"title": "The Lord of the Rings: The Return of the King", "author": "J.R.R. Tolkien", "genre": "Fantasy", "description": "The final battle for Middle-earth."},
    {"title": "The Silmarillion", "author": "J.R.R. Tolkien", "genre": "Fantasy", "description": "The creation and myths of Middle-earth."}
]


        for book_data in sample_books:
            book, created = Book.objects.get_or_create(
                title=book_data["title"],
                defaults={
                    "author": book_data["author"],
                    "genre": book_data["genre"],
                    "description": book_data["description"],
                    "is_borrowed": False,
                },
            )
            if created:
                self.stdout.write(self.style.SUCCESS(f"Added {book.title}"))
            else:
                self.stdout.write(self.style.WARNING(f"{book.title} already exists."))